// Definition fo all action type constants

export const AUTH_START = 'AUTH_START';
export const AUTH_DONE = 'AUTH_DONE';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_USER = 'AUTH_USER';
export const SIGN_OUT_USER = 'SIGN_OUT_USER';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const SEARCH_FOR_BOOKS_IN_PROCESS = 'SEARCH_FOR_BOOKS_IN_PROCESS';
export const SEARCH_FOR_BOOKS_SUCCESS = 'SEARCH_FOR_BOOKS_SUCCESS';
export const SEARCH_FOR_BOOKS_FAILURE = 'SEARCH_FOR_BOOKS_FAILURE';

export const INIT_USER_STATE = 'INIT_USER_STATE';

// Handle Categories
export const ADD_CAT_START = 'ADD_CAT_START';
export const ADD_CAT_TO_STORE = 'ADD_CAT_TO_STORE';
export const ADD_CAT_ERROR = 'ADD_CAT_ERROR';

export const FETCH_CATS_START = 'FETCH_CATS_START';
export const FETCH_CATS_TO_STORE = 'FETCH_CATS_TO_STORE';
export const FETCH_CATS_DONE = 'FETCH_CATS_DONE';
export const FETCH_CATS_ERROR = 'FETCH_CATS_ERROR';

// Handle Books
export const GET_BOOK_DESC = 'GET_BOOK_DESC';

export const ADD_BOOK_TO_LIBRARY = 'ADD_BOOK_TO_LIBRARY';
export const ADD_BOOK_START = 'ADD_BOOK_START';
export const ADD_BOOK_TO_STORE = 'ADD_BOOK_TO_STORE';
export const ADD_BOOK_ERROR = 'ADD_BOOK_ERROR';

export const FETCH_BOOKS_LIST_START = 'FETCH_BOOKS_LIST_START';
export const FETCH_BOOKS_LIST_TO_STORE = 'FETCH_BOOKS_LIST_TO_STORE';
export const FETCH_BOOKS_LIST_DONE = 'FETCH_BOOKS_LIST_DONE';
export const FETCH_BOOKS_LIST_ERROR = 'FETCH_BOOKS_LIST_ERROR';

export const FETCH_BOOKS_DETAILS_START = 'FETCH_BOOKS_DETAILS_START';
export const FETCH_BOOKS_DETAILS_TO_STORE = 'FETCH_BOOKS_DETAILS_TO_STORE';
export const FETCH_BOOKS_DETAILS_DONE = 'FETCH_BOOKS_DETAILS_DONE';
export const FETCH_BOOKS_DETAILS_ERROR = 'FETCH_BOOKS_DETAILS_ERROR';
